### ISSUE TITLE
Code disappeared?

### ISSUE THREAD

**Issue by antch** [mikehaas763/ngconf-2019-turning-an-aircraft-carrier#1]
Hi, I was at your talk at ng-conf (and I actually spoke to you briefly at your booth) and was hoping to look at this project -- are there any plans for the code to be made available again?

**Comment by dopsonbr** [comment]
I have the same question as antch. I just watched the ng-conf talk and would love to take a look at the code.

**Comment by mikehaas763** [comment]
Should be resolved. Sorry for the delay.
